### PR TITLE
feat(conform): add ability to toggle autoformat

### PR DESCRIPTION
**Pull request by KevinNitroG**
Ref:
- https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#autoformat-with-extra-features
- https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save

I just quickly add those :) Please test it before merging. I haven't tested it yet!

### CODE REVIEW

**Comment by KevinNitroG** [comment]
Also check the code convention :>

**Comment by Alexis12119** [comment]
It has Merge conflict

**Comment by KevinNitroG** [comment]
> Is it not possible to only use one command for it?

It can ig. I will resolve the conflict and try to implement it.

**Comment by KevinNitroG** [comment]
@Alexis12119 I have made changes. Please review it ((:

Don't trust me, I don't trust myself either.

**Comment by KevinNitroG** [comment]
image

there's mini multiverse conflict on my local branch =))

**Comment by KevinNitroG** [comment]
I think you would rather "squash and merge" for a better look in the git log

**Pull request merged**
