### PR TITLE
fix(lsp): make inlayhint keymap work

### PR DESCRIPTION
**Pull request by KevinNitroG**
Hi, could you try this? thank you.

### CODE REVIEW

**Comment by Alexis12119** [comment]
It's throwing this error. It's already working though.
```lua


E5108: Error executing lua: ...im-linux64/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:375: bufnr: expected number, got boolean
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	...im-linux64/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:375: in function 'enable'
	/home/blan_11/.config/nvim/lua/plugins/lsp/init.lua:13: in function </home/blan_11/.config/nvim/lua/plugins/lsp/init.lua:11>
```

**Comment by Alexis12119** [comment]
Just small adjustment here. Thanks for the idea.

```lua
    vim.keymap.set("n", "<leader>lh", function()
      if vim.fn.has "nvim-0.10" == 1 then
        vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled())
      end
    end, { desc = "LSP | Inlay Hints", silent = true })
```

**Comment by KevinNitroG** [comment]
I'm using neovim 0.10.0 on Windows. The previous commit (before this PR), it didn't work for me :))
image

After I change the code a bit (this PR), it worked fine with my machine. But seemed that it didn't work on yours 🫠

After pulling your latest code, it doesn't work on my machine lol
image

**Comment by KevinNitroG** [comment]
BTW I think the desc of the keymap should be sth like `toggle inlay hint`

**Comment by Alexis12119** [comment]
> BTW I think the desc of the keymap should be sth like `toggle inlay hint`

I'll try my best to make it work on the current version of neovim.

**Comment by Alexis12119** [comment]
@KevinNitroG, can you try this one first?
```lua
        local ok, _ = pcall(vim.lsp.inlay_hint.enable, not vim.lsp.inlay_hint.is_enabled())
        if ok then
          vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
        else
          vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled())
        end
```

**Comment by KevinNitroG** [comment]
> @KevinNitroG, can you try this one first?
> 
> ```lua
> local ok = pcall(vim.lsp.inlay_hint.enable, not vim.lsp.inlay_hint.is_enabled())
> if ok then
>   vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
> else
>   vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled())
> end
> ```

I will be back to windows and test that out later, thank you :)
also in my neovim (install with yay - 0.10.0-2) it doesn't work =)) (at commit f6acf827608fff22d2f1bce17d4223f89ccfa6f7: fix typo)

**Comment by Alexis12119** [comment]
> > @KevinNitroG, can you try this one first?
> > ```lua
> > local ok = pcall(vim.lsp.inlay_hint.enable, not vim.lsp.inlay_hint.is_enabled())
> > if ok then
> >   vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
> > else
> >   vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled())
> > end
> > ```
> 
> I will be back to windows and test that out later, thank you :) also in my neovim (install with yay - 0.10.0-2) it doesn't work =)) (at commit [f6acf82](https://github.com/Alexis12119/nvim-config/commit/f6acf827608fff22d2f1bce17d4223f89ccfa6f7): fix typo) image

try `git pull` to get the latest changes. What i did was run the compatible command with `pcall` so when it throws an error then it'll use the command that's compatible with nightly, but if it's fine then it'll run the command that's fine in the current `0.10` version of `neovim`.

**Comment by KevinNitroG** [comment]
I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))


https://github.com/Alexis12119/nvim-config/assets/86353526/102bf1d7-2c0b-4915-9a88-5b54aefb9713

**Comment by Alexis12119** [comment]
> I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> 2024-05-20.18-40-36.mp4

try it in a lua file.

**Comment by KevinNitroG** [comment]
> > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > 2024-05-20.18-40-36.mp4
> 
> try it in a lua file.

Here I tried to run in a lua file.

https://github.com/Alexis12119/nvim-config/assets/86353526/86fd304c-ddb4-42c9-820a-70812ff36288

**Comment by Alexis12119** [comment]
> > > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > > 2024-05-20.18-40-36.mp4
> > 
> > 
> > try it in a lua file.
> 
> Here I tried to run in a lua file.
> 2024-05-20.18-46-23.mp4

I mean file like `lsp/init.lua`. What your exact neovim version?

**Comment by Alexis12119** [comment]
@KevinNitroG, Looks like nothing is really happening. I'll use the latest version to fix it.

**Comment by KevinNitroG** [comment]
> > > > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > > > 2024-05-20.18-40-36.mp4
> > > 
> > > 
> > > try it in a lua file.
> > 
> > 
> > Here I tried to run in a lua file.
> > 2024-05-20.18-46-23.mp4
> 
> I mean file like `lsp/init.lua`. What's your exact neovim version?

I guess it will be same as above issue in video 🌝 I will test it later, I'm having dinner (my mom call 🥶)

My neovim:
- 0.10.0-2 in linux
- 0.10 ? in Windows (haven't test the latest code) (install with scoop)

**Comment by Alexis12119** [comment]
> > > > > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > > > > 2024-05-20.18-40-36.mp4
> > > > 
> > > > 
> > > > try it in a lua file.
> > > 
> > > 
> > > Here I tried to run in a lua file.
> > > 2024-05-20.18-46-23.mp4
> > 
> > 
> > I mean file like `lsp/init.lua`. What's your exact neovim version?
> 
> I guess it will be same as above issue in video 🌝 I will test it later, I'm having dinner (my mom called 🥶)
> 
> My neovim:
> 
>     * 0.10.0-2 on linux
> 
>     * 0.10 ? on Windows (haven't tested the latest code) (install with scoop)

Alright, I'll try to fix it.

**Comment by KevinNitroG** [comment]
> > > > > > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > > > > > 2024-05-20.18-40-36.mp4
> > > > > 
> > > > > 
> > > > > try it in a lua file.
> > > > 
> > > > 
> > > > Here I tried to run in a lua file.
> > > > 2024-05-20.18-46-23.mp4
> > > 
> > > 
> > > I mean file like `lsp/init.lua`. What's your exact neovim version?
> > 
> > 
> > I guess it will be same as above issue in video 🌝 I will test it later, I'm having dinner (my mom called 🥶)
> > My neovim:
> > ```
> > * 0.10.0-2 on linux
> > 
> > * 0.10 ? on Windows (haven't tested the latest code) (install with scoop)
> > ```
> 
> Alright, I'll try to fix it. Eat well.

Next time I will create an issue along with PR. 😵‍💫

**Comment by Alexis12119** [comment]
> > > > > > > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > > > > > > 2024-05-20.18-40-36.mp4
> > > > > > 
> > > > > > 
> > > > > > try it in a lua file.
> > > > > 
> > > > > 
> > > > > Here I tried to run in a lua file.
> > > > > 2024-05-20.18-46-23.mp4
> > > > 
> > > > 
> > > > I mean file like `lsp/init.lua`. What's your exact neovim version?
> > > 
> > > 
> > > I guess it will be same as above issue in video 🌝 I will test it later, I'm having dinner (my mom called 🥶)
> > > My neovim:
> > > ```
> > > * 0.10.0-2 on linux
> > > 
> > > * 0.10 ? on Windows (haven't tested the latest code) (install with scoop)
> > > ```
> > 
> > 
> > Alright, I'll try to fix it. Eat well.
> 
> Next time I will create an issue along with PR. 😵‍💫

Try my latest fix if you finished your dinner.

**Comment by Alexis12119** [comment]
> > > > > > > > > I have tested the commit [feat: make it work on 0.10 stable.](https://github.com/Alexis12119/nvim-config/commit/0c6ec7f6ad45f8f4575f0160d401fcf59da84603) on my neovim (linux). It doesn't toggle. It's like, turn off and on :))
> > > > > > > > > 2024-05-20.18-40-36.mp4
> > > > > > > > 
> > > > > > > > 
> > > > > > > > try it in a lua file.
> > > > > > > 
> > > > > > > 
> > > > > > > Here I tried to run in a lua file.
> > > > > > > 2024-05-20.18-46-23.mp4
> > > > > > 
> > > > > > 
> > > > > > I mean file like `lsp/init.lua`. What's your exact neovim version?
> > > > > 
> > > > > 
> > > > > I guess it will be same as above issue in video 🌝 I will test it later, I'm having dinner (my mom called 🥶)
> > > > > My neovim:
> > > > > ```
> > > > > * 0.10.0-2 on linux
> > > > > 
> > > > > * 0.10 ? on Windows (haven't tested the latest code) (install with scoop)
> > > > > ```
> > > > 
> > > > 
> > > > Alright, I'll try to fix it. Eat well.
> > > 
> > > 
> > > Next time I will create an issue along with PR. 😵‍💫
> > 
> > 
> > Try my latest fix if you finished your dinner.
> 
> Confirm it works on both my Linux and Windows. Thank you :)) The dinner was very delicious btw

Nice, now I can finally relax again.

**Pull request merged**
