### PR TITLE
feat(plugin): migrate from `olimorris/persisted.nvim` to `rmagatti/auto-session`

### PR DESCRIPTION
**Pull request by KevinNitroG**
re #44

Note that `rmagatti/auto-session` is disabled by default

### CODE REVIEW

**Comment by KevinNitroG** [comment]
wait!!

**Comment by KevinNitroG** [comment]
Wait I forget to add keymap for toggle;)) I'm having dinner

**Comment by KevinNitroG** [comment]
> Why did you comment the code for showing `group` icon for `sessions`?

Because you don't use session manager plugin. So I make it enable up to you.

Btw I forgot to change the keymap for toogle one. I will fix it later. I'm having dinner 💫

**Comment by Alexis12119** [comment]
yeah, I forgot haha. Eat well.

**Comment by KevinNitroG** [comment]
Alright I think it's good to be merged now

**Pull request merged**
