### PR TITLE
feat(statusline): show buffer's linters

### PR DESCRIPTION
**Pull request by KevinNitroG**
Oops :))

I think it will work fine.

### CODE REVIEW

**Comment by KevinNitroG** [comment]
image

image


Here's examples

**Comment by KevinNitroG** [comment]
I think I need to change the way to get linters by fts. Because for example, the file whose ft is yaml.ghaction cannot get the yaml only linter.

I'm gonna find a way to split the string up and to get all individual fts.

**Comment by KevinNitroG** [comment]
Ok I think it's look good now (: I guess

**Comment by Alexis12119** [comment]
Alright, I hope it really good now. Thanks for this.

**Pull request merged**
