### PR TITLE
feat(which-key): trigger on `[`, `]`

### PR DESCRIPTION
**Pull request by KevinNitroG**
Currently, when which-key hasn't loaded yet, it cannot be triggered to load when using `[`, `]` keys. Example using `mini-bracketed`, lsp's sth,...

image

### CODE REVIEW

**Comment by Alexis12119** [comment]
I see, I'm not using that plugin that's why I didn't noticed. But, thanks for the fix and I'll merge it now.

**Comment by KevinNitroG** [comment]
> I see, I'm not using that plugin that's why I didn't noticed. But, thanks for the fix and I'll merge it now.

Actually I mean the [`nvim-treesitter`](https://github.com/Alexis12119/nvim-config/blob/3b565ee737f561e93cf8aa81cefb9d552aa0c41a/lua/plugins/nvim-treesitter.lua#L96-L130C9) features, not LSP's one 😅

**Comment by Alexis12119** [comment]
> > I see, I'm not using that plugin that's why I didn't noticed. But, thanks for the fix and I'll merge it now.
> 
> Actually I meant the [`nvim-treesitter`](https://github.com/Alexis12119/nvim-config/blob/3b565ee737f561e93cf8aa81cefb9d552aa0c41a/lua/plugins/nvim-treesitter.lua#L96-L130C9) features, not LSP's one 😅

Good thing `0.11` and `0.10` now have the same way to enable `inlay_hints`.

**Comment by KevinNitroG** [comment]
> > > I see, I'm not using that plugin that's why I didn't noticed. But, thanks for the fix and I'll merge it now.
> > 
> > 
> > Actually I meant the [`nvim-treesitter`](https://github.com/Alexis12119/nvim-config/blob/3b565ee737f561e93cf8aa81cefb9d552aa0c41a/lua/plugins/nvim-treesitter.lua#L96-L130C9) features, not LSP's one 😅
> 
> Good thing `0.11` and `0.10` now have the same way to enable `inlay_hints`.

We have had a hard time 🥴

**Pull request merged**
